name: Playwright CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adaptez selon votre version

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Installer les navigateurs Playwright
      - name: Install Playwright browsers
        run: npx playwright install

      # Étape 5 : Exécuter les tests
      - name: Run Playwright tests
        run: xvfb-run npx playwright test  #--max-failures=1

      - name: Install Allure
        run: npm install -g allure-commandline
        if: always()
      
      - name: Generate Allure Report
        run: allure generate allure-results --clean
        if: always()
      
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
        if: always()
      
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
        if: always()